package com.learninglogs.model;

public class Entry {

    private int id;
    private int topicId;
    private String text;

    // Constructor for new entries (ID will be generated by DB)
    public Entry(int topicId, String text) {
        this.topicId = topicId;
        this.text = text;
    }

    // Constructor for fetching entries from DB (with ID)
    public Entry(int id, int topicId, String text) {
        this.id = id;
        this.topicId = topicId;
        this.text = text;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getTopicId() {
        return topicId;
    }

    public void setTopicId(int topicId) {
        this.topicId = topicId;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return "Entry{" +
                "id=" + id +
                ", topicId=" + topicId +
                ", text='" + text + '\'' +
                '}';
    }
}
